// Generated by scripts/make-banner-artwork.mjs. Do not edit by hand.
//
// Sizes and weights of everything in public/marketing/, so the console can
// label a download without reading the file — public/ is not in the deployed
// function bundle, so at request time there is nothing to read.

export type BannerFileFacts = {
  bytes: number;
  /** The page, in inches. Wider than nothing, taller than the banner. */
  widthIn: number;
  heightIn: number;
  /** What is actually seen once it is in the stand. */
  visibleIn: number;
};

export const BANNER_FILES: Record<string, BannerFileFacts> = {
  "banner-signed-and-covered-33-5x80.pdf": { bytes: 101441, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-signed-and-covered-33-5x80.png": { bytes: 26980, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-signed-and-covered-39x80.pdf": { bytes: 102904, widthIn: 39, heightIn: 84, visibleIn: 80 },
  "banner-signed-and-covered-39x80.png": { bytes: 31425, widthIn: 39, heightIn: 84, visibleIn: 80 },
  "banner-signed-and-covered-47x80.pdf": { bytes: 102793, widthIn: 47, heightIn: 84, visibleIn: 80 },
  "banner-signed-and-covered-47x80.png": { bytes: 37199, widthIn: 47, heightIn: 84, visibleIn: 80 },
  "banner-signed-and-covered-60x80.pdf": { bytes: 109744, widthIn: 60, heightIn: 84, visibleIn: 80 },
  "banner-signed-and-covered-60x80.png": { bytes: 42375, widthIn: 60, heightIn: 84, visibleIn: 80 },
  "banner-signed-and-covered-11x17.pdf": { bytes: 98373, widthIn: 11, heightIn: 19, visibleIn: 17 },
  "banner-signed-and-covered-11x17.png": { bytes: 6756, widthIn: 11, heightIn: 19, visibleIn: 17 },
  "banner-how-it-works-33-5x80.pdf": { bytes: 97978, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-how-it-works-33-5x80.png": { bytes: 22876, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-for-businesses-33-5x80.pdf": { bytes: 100083, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-for-businesses-33-5x80.png": { bytes: 25264, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-backdrop-1-33-5x80.pdf": { bytes: 69976, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-backdrop-1-33-5x80.png": { bytes: 16940, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-backdrop-2-33-5x80.pdf": { bytes: 50949, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-backdrop-2-33-5x80.png": { bytes: 17209, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-backdrop-3-33-5x80.pdf": { bytes: 68870, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
  "banner-backdrop-3-33-5x80.png": { bytes: 16320, widthIn: 33.5, heightIn: 84, visibleIn: 80 },
};
