// Generated by scripts/make-brand-assets.mjs. Do not edit by hand.
//
// Sizes and pixel dimensions of everything in public/brand/, so the download
// page can label a link without reading the file — public/ is not in the
// deployed function bundle, so at request time there is nothing to read.

export type BrandFileFacts = { bytes: number; width: number; height: number };

export const BRAND_FILES: Record<string, BrandFileFacts> = {
  "i-waiver-mark.svg": { bytes: 1468, width: 107, height: 107 },
  "i-waiver-mark-reversed.svg": { bytes: 1468, width: 107, height: 107 },
  "i-waiver-mark.png": { bytes: 186278, width: 3414, height: 3414 },
  "i-waiver-mark-reversed.png": { bytes: 179732, width: 3414, height: 3414 },
  "i-waiver-logo.svg": { bytes: 6706, width: 3894, height: 1980 },
  "i-waiver-logo-reversed.svg": { bytes: 6706, width: 3894, height: 1980 },
  "i-waiver-logo.png": { bytes: 170030, width: 3894, height: 1980 },
  "i-waiver-logo-light.pdf": { bytes: 21976, width: 3894, height: 1980 },
  "i-waiver-logo-light.jpg": { bytes: 224040, width: 3894, height: 1980 },
  "i-waiver-logo-reversed.png": { bytes: 164137, width: 3894, height: 1980 },
  "i-waiver-logo-dark.pdf": { bytes: 21976, width: 3894, height: 1980 },
  "i-waiver-logo-dark.jpg": { bytes: 223157, width: 3894, height: 1980 },
  "i-waiver-profile-light.jpg": { bytes: 148202, width: 2048, height: 2048 },
  "i-waiver-profile-light.png": { bytes: 105483, width: 2048, height: 2048 },
  "i-waiver-profile-dark.jpg": { bytes: 147112, width: 2048, height: 2048 },
  "i-waiver-profile-dark.png": { bytes: 106294, width: 2048, height: 2048 },
};
